/**
 *
 * $Id$
 */
package ddsm.validation;


/**
 * A sample validator interface for {@link ddsm.ChefRecipe}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ChefRecipeValidator {
    boolean validate();

    boolean validateRecipeUrl(String value);
    boolean validateRecipePath(String value);
}
