/**
 *
 * $Id$
 */
package ddsm.validation;


/**
 * A sample validator interface for {@link ddsm.Crontab}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CrontabValidator {
    boolean validate();

    boolean validateMin(int value);
    boolean validateHour(int value);
    boolean validateDayOfMonth(int value);
    boolean validateMonth(int value);
    boolean validateDayOfWeek(int value);
}
