/**
 *
 * $Id$
 */
package ddsm.validation;

import ddsm.CloudElement;
import ddsm.Property;
import ddsm.Resource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ddsm.DDSM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DDSMValidator {
    boolean validate();

    boolean validateCloudelement(EList<CloudElement> value);
    boolean validateModelId(String value);
    boolean validateDescription(String value);
    boolean validateProperties(EList<Property> value);
    boolean validateResources(EList<Resource> value);
}
