/**
 *
 * $Id$
 */
package ddsm.validation;


/**
 * A sample validator interface for {@link ddsm.Nimbus}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NimbusValidator {
    boolean validate();

    boolean validateTaskTimeout(int value);
    boolean validateSupervisorFrequency(int value);
    boolean validateQueueSize(int value);
    boolean validateMonitorFrequency(int value);
    boolean validateRetryTimes(int value);
    boolean validateRetryInterval(int value);
}
