/**
 *
 * $Id$
 */
package ddsm.validation;

import ddsm.Property;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ddsm.Provider}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProviderValidator {
    boolean validate();

    boolean validateCredentialsPath(String value);
    boolean validateName(String value);
    boolean validateProperty(EList<Property> value);
    boolean validateProviderId(String value);
}
