/**
 *
 * $Id$
 */
package ddsm.validation;


/**
 * A sample validator interface for {@link ddsm.Resource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceValidator {
    boolean validate();

    boolean validateResourceId(String value);
    boolean validateDownloadCommand(String value);
    boolean validateCreateCommand(String value);
    boolean validateConfigureCommand(String value);
    boolean validateInstallCommand(String value);
    boolean validateStartCommand(String value);
    boolean validateStopCommand(String value);
}
