/**
 *
 * $Id$
 */
package ddsm.validation;

import ddsm.VMSize;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link ddsm.VM}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VMValidator {
    boolean validate();

    boolean validateIs64os(String value);
    boolean validateImageId(String value);
    boolean validateMaxCores(String value);
    boolean validateMaxRam(String value);
    boolean validateMaxStorage(String value);
    boolean validateMinCores(String value);
    boolean validateMinRam(String value);
    boolean validateMinStorage(String value);
    boolean validateOs(String value);
    boolean validatePrivateKey(String value);
    boolean validateProviderSpecificTypeName(String value);
    boolean validateSecurityGroup(String value);
    boolean validateSshKey(String value);
    boolean validatePublicAddress(String value);
    boolean validateGenericSize(VMSize value);
    boolean validateInstances(int value);
    boolean validatePublicPorts(EList<Integer> value);
}
