<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="diceDeploymentSpecificModel" nsURI="http://ddsm/1.0" nsPrefix="diceDeploymentSpecificModel">
  <eClassifiers xsi:type="ecore:EClass" name="CloudElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resource" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Resource"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Property"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cloudElementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propertyId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//CloudElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedport" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ProvidedPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedexecutionplatform"
        upperBound="-1" eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ProvidedExecutionPlatform"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InternalComponent" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredport" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//RequiredPort"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="internalcomponent" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//InternalComponent"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredexecutionplatform"
        upperBound="-1" eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//RequiredExecutionPlatform"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionPlatform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="owner" eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionPlatformId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Port">
    <eStructuralFeatures xsi:type="ecore:EReference" name="component" eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredPort" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedPort" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Port"/>
  <eClassifiers xsi:type="ecore:EClass" name="RequiredExecutionPlatform" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ExecutionPlatform"/>
  <eClassifiers xsi:type="ecore:EClass" name="ProvidedExecutionPlatform" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ExecutionPlatform">
    <eStructuralFeatures xsi:type="ecore:EReference" name="offer" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Offer"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Relationship" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//CloudElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedport" eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ProvidedPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredport" eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//RequiredPort"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relationshipId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExecutionBinding" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//CloudElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredexecutionplatform"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//RequiredExecutionPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedexecutionplatform"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ProvidedExecutionPlatform"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bindingId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalComponent" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" lowerBound="1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Provider"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Provider">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="credentialsPath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Property"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VM" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ExternalComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="is64os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="imageId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxRam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxStorage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minCores" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minRam" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minStorage" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="os" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="privateKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providerSpecificTypeName"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="securityGroup" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sshKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="publicAddress" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="instances" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DDSM">
    <eStructuralFeatures xsi:type="ecore:EReference" name="cloudelement" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//CloudElement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provider" upperBound="-1"
        eType="ecore:EClass /DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Provider"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="modelId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LifeCycle" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="downloadCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="installCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopCommand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChefRecipe" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//Resource">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recipeUrl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="recipePath" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Offer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StormSupervisor" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="MediumHost" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//VM"/>
  <eClassifiers xsi:type="ecore:EClass" name="SmallHost" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//VM"/>
  <eClassifiers xsi:type="ecore:EClass" name="LargeHost" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//VM"/>
  <eClassifiers xsi:type="ecore:EClass" name="StormNimbus" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Zookeeper" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="Kafka" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//InternalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="LoadBalancer" eSuperTypes="/DiceDeploymentSpecificModel/model/diceDeploymentSpecificModel.ecore#//ExternalComponent"/>
</ecore:EPackage>
