<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spark" nsURI="http://io.github.dice-project/dtsm/spark/1.0"
    nsPrefix="dtsm.spark">
  <eAnnotations source="Function" references="#//RDD/generates #//ParallelOperation">
    <details key="LineageAssociationClass"/>
    <details key="inputRDD_ID"/>
    <details key="outputRDD_ID"/>
  </eAnnotations>
  <eAnnotations source="RDDOpsRestriction" references="#//RDD">
    <details key="ByKeyOpsRestriction"/>
  </eAnnotations>
  <eAnnotations source="FunctionType" references="#//ParallelOperation">
    <details key="InferredParallelOpsType"/>
  </eAnnotations>
  <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
    <details key="name" value="DiceDomainModel::DTSM::Spark"/>
    <details key="profileName" value="DICE::DICE_UML_Extensions::DTSM::Spark"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DIAmain" eSuperTypes="#//DriverProgram">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents the root of the Spark application and has an associated DriverProgram to execute."/>
    </eAnnotations>
    <eOperations name="SparkConfConstructor" lowerBound="1"/>
    <eOperations name="SparkContextConstructor"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sparkDependency" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="groupId = org.apache.spark&#xA;artifactId = spark-core_2.10&#xA;version = 1.4.1"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hadoopClientDependency"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="groupId = org.apache.hadoop&#xA;artifactId = hadoop-client&#xA;version = &lt;your-hdfs-version>"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sparkImports" lowerBound="1"
        upperBound="3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="import org.apache.spark.api.java.JavaSparkContext&#xA;import org.apache.spark.api.java.JavaRDD&#xA;import org.apache.spark.SparkConf"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constructs" lowerBound="1"
        eType="#//SparkContext"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="uses" lowerBound="1" eType="#//DriverProgram"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DistributedDataset">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents the dataset the Spark application have to process. "/>
    </eAnnotations>
    <eOperations name="ParallelOpSet" lowerBound="1" upperBound="-1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="" lowerBound="1" upperBound="-1"
        eType="#//ExternalData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stems from" lowerBound="1"
        upperBound="-1" eType="#//ExternalData"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SparkDistObjType"/>
  <eClassifiers xsi:type="ecore:EClass" name="ParallelOperation" eSuperTypes="#//Function">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="A generic operation performing some trasformation in paralled on RDDs."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameter" lowerBound="1"
        upperBound="-1" eType="#//Function" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputRDD" lowerBound="1"
        upperBound="-1" eType="#//RDDtype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputRDD" lowerBound="1"
        upperBound="-1" eType="#//RDDtype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receives" lowerBound="1"
        upperBound="-1" eType="#//RDD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produces" lowerBound="1"
        upperBound="-1" eType="#//outputRDD"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" lowerBound="1" upperBound="-1"
        eType="#//RDD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalData">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an external data source from which RDDs can be created."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Path"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SparkFunctionType">
    <eLiterals name="transformation"/>
    <eLiterals name="action" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="count" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return the number of elements in an RDD."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="counter" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="filter" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return a new dataset formed by selecting those elements of the source RDD on which a given function returns true."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="collect" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return all the elements of the dataset as an array."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="flatMap" eSuperTypes="#//map">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Similar to map, but each input item can be mapped to 0 or more output items instead of just a single item."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mapToPair" eSuperTypes="#//map">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return a new RDD by applying a function to all elements of this RDD."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pair" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByteArray"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="reduceByKey" eSuperTypes="#//reduce">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="When called on a dataset of (K, V) pairs, returns a dataset of (K, V) pairs where the values for each key are aggregated using a given reduce function"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reducingKey" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="saveAsTextFile" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Write the elements of the dataset as a text file (or set of text files) in a given directory in a filesystem"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="map" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return a new RDD formed by passing each element of the source RDD through a function func."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="reduce" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This operation aggregates the elements of the RDD on which it is execute using a given reduce function."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DriverProgram">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="The DriverProgram is the main application that declares the transformations and actions on RDDs using a instance of the SparkContext and submits such requests to the master which manages the cluster scheduling tasks among Workers and provides the SparkContext."/>
    </eAnnotations>
    <eOperations name="main"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes" lowerBound="1"
        upperBound="-1" eType="#//ParallelOperation"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clusterConfig" lowerBound="1"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EChar"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ParallelizableCollection"
        lowerBound="1" upperBound="-1" eType="#//SparkVar"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="works on" lowerBound="1"
        upperBound="-1" eType="#//DistributedDataset" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distData" lowerBound="1"
        upperBound="-1" eType="#//SparkDistObjType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="DriverMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SparkVar">
    <eLiterals name="Broadcast"/>
    <eLiterals name="Accumulator" value="1"/>
    <eLiterals name="ParallelizableCollection" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SparkContext">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="The SparkContext is the main entry point for Spark functionality. A SparkContext represents the connection to a Spark cluster. It can be used for example to create RDDs from a datastore table (i.e. a Cassandra table)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        eType="#//ClusterConfig" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Function">
    <eAnnotations source="org.apache.spark.api.java.function"/>
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="The Spark Function is an interface representing a generic operation provided by Spark appliable on RDDs."/>
    </eAnnotations>
    <eOperations name="Function"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="coalesce" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This Spark operation decreases the number of partitions in an input RDD."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="groupByKey" eSuperTypes="#//coalesce">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="When called on a dataset of (K, V) pairs, returns a dataset of (K, Iterable&lt;V>) pairs. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupingKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="aggregateByKey" eSuperTypes="#//coalesce">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="When called on a dataset of (K, V) pairs, returns a dataset of (K, U) pairs where the values for each key are aggregated using a given combine functions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregatingKey"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mapPartitions" eSuperTypes="#//map">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Similar to map, but runs separately on each partition (block) of the RDD."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="mapPartitionsWithIndex" eSuperTypes="#//mapPartitions">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Similar to mapPartitions, but also provides the executed function with an integer value representing the index of the partition"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="sample" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Sample a fraction of the input RDD, with or without replacement, using a given random number generator seed."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="union" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return a new dataset that contains the union of the elements in the RDD on which it is called and the argument RDD."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Intersection" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Return a new dataset that contains the intersection of the elements in the RDD on which it is called and the argument RDD."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SparkStorageLevel">
    <eLiterals name="MEMORY_ONLY "/>
    <eLiterals name=" MEMORY_AND_DISK " value="1"/>
    <eLiterals name=" MEMORY_ONLY_SER " value="2"/>
    <eLiterals name=" MEMORY_AND_DISK_SER " value="3"/>
    <eLiterals name=" DISK_ONLY " value="4"/>
    <eLiterals name=" MEMORY_ONLY_2, MEMORY_AND_DISK_2, " value="5"/>
    <eLiterals name="OFF_HEAP" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RDDtype">
    <eLiterals name="PythonObj" value="1"/>
    <eLiterals name="JavaObj"/>
    <eLiterals name="EEnumLiteral0" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RDD">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represend and RDD ( Resilient Distributed Dataset ) and is the primary abstraction within the Spark framework. An RDD is a fault-tolerant, possibly distributed, set of items that can be processed in parallel. They can be for example generated from data stored in HDFS."/>
    </eAnnotations>
    <eOperations name="cache"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Type" eType="#//RDDtype"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generates" lowerBound="1"
        eType="#//RDD"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ID" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageLevel" eType="#//SparkStorageLevel"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="outputRDD">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents the output RDD of the Spark application that can be stored."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineage" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ClusterConfig">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents the configuration of the Spark cluster managed by the Master, like the number of nodes and characteristics of each node."/>
    </eAnnotations>
    <eOperations name="wholeTextFiles"/>
    <eOperations name="textFile"/>
    <eOperations name="sequenceFile"/>
    <eOperations name="hadoopRDD">
      <eAnnotations source="takes an arbitrary JobConf and input format class, key class and value class. Set these the same way you would for a Hadoop job with your input source. You can also use JavaSparkContext.newAPIHadoopRDD for InputFormats based on the “new” MapReduce API (org.apache.hadoop.mapreduce)."/>
    </eOperations>
    <eOperations name="objectFile"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ExecutorMemory" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ClusterURL" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="StorageMemoryFraction"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ShuffleMemoryFraction"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//ELong"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Master" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="AppName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loop">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity simply represent a loop executed by the Spark application. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="executes" lowerBound="1"
        eType="#//Function" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processes" lowerBound="1"
        upperBound="-1" eType="#//RDD" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runs" upperBound="-1" eType="#//Loop"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PairRDD" eSuperTypes="#//RDD">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="RDD that are just (key, value) pairs, for which Spark provides extra functions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="keyType" lowerBound="1"
        upperBound="-1" eType="#//RDDtype"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valueType" eType="#//RDDtype"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="sort" eSuperTypes="#//ParallelOperation">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="When this operation is called on a dataset of (K, V) pairs where, it returns a dataset of (K, V) pairs sorted by keys in ascending or descending order"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
