/**
 *
 * $Id$
 */
package tosca.validation;

import org.eclipse.emf.common.util.EList;

import tosca.Input;

/**
 * A sample validator interface for {@link tosca.Operation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OperationValidator {
    boolean validate();

    boolean validateOperation_name(String value);
    boolean validateDescription(String value);
    boolean validateOperation_hasInput(EList<Input> value);
    boolean validateScript(String value);
    boolean validateExecutor(String value);
}
