<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://io.github.dice-project/dtsm/core/1.0" nsPrefix="dtsm.core">
  <eAnnotations source="PropertyAnnotations">
    <details key="Sigma"/>
    <details key="PredecessorsList"/>
    <details key="Alpha"/>
    <details key="IdleTime"/>
    <details key="MTTF"/>
    <details key="MTTR"/>
    <details key="TBF"/>
  </eAnnotations>
  <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
    <details key="name" value="DiceDomainModel::DTSM::Core"/>
    <details key="profileName" value="DICE::DICE_UML_Extensions::DTSM::Core"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DIAElement" abstract="true">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents a generic element of the DIA at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::DIAElement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageNode" eSuperTypes="#//DataSource">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents a storage node in the DIA implemented by a specific storage technology at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::StorageNode"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationNode" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an element of the DIA performing a computation task by employing a specific data processing technology at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::ComputationNode"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessDataSources" upperBound="-1"
        eType="#//DataSource"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetTech" eType="#//TechType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procType" eType="#//ProcessingType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processData" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessors" upperBound="-1"
        eType="#//ComputationNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realise" eType="#//Workflow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeOutput" eType="#//StorageNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an element of the DIA acting as a data source at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::SourceNode"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="ecore:EEnum ../../io.github.dice-project.dpim/model/dpim.ecore#//SourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstraintsType">
    <eLiterals name="maxIteration"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComputationalNodeType">
    <eLiterals name="HadoopMR"/>
    <eLiterals name="Storm" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ManagementLayerType">
    <eLiterals name="spark"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="JobScheduleType">
    <eLiterals name="runtime"/>
    <eLiterals name="speculative" value="1"/>
    <eLiterals name="redundant" value="2"/>
    <eLiterals name="fair" value="3"/>
    <eLiterals name="capacity" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AccessScheduleType"/>
  <eClassifiers xsi:type="ecore:EEnum" name="FunctionSpecType">
    <eLiterals name="map"/>
    <eLiterals name="reduce" value="1"/>
    <eLiterals name="combine" value="2"/>
    <eLiterals name="partition" value="3"/>
    <eLiterals name="report" value="4"/>
    <eLiterals name="collectOutput" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SourceNode" eSuperTypes="#//DataSource"/>
  <eClassifiers xsi:type="ecore:EClass" name="Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="Metric"/>
  <eClassifiers xsi:type="ecore:EClass" name="SimpleProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isMeasured" lowerBound="1"
        eType="#//Metric"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompositeProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="isComposedOf" lowerBound="2"
        upperBound="-1" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="compositionFunction" eType="#//CompositionFunction"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNode" lowerBound="1"
        upperBound="-1" eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedProperty" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredProperty" upperBound="-1"
        eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessors" upperBound="-1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produceOutput" eType="ecore:EClass ../../io.github.dice-project.dpim/model/dpim.ecore#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="performedOperation" lowerBound="1"
        eType="#//WorkflowOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CompositionFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SourceType">
    <eLiterals name="sharedStorage"/>
    <eLiterals name="dataStream" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessingType">
    <eLiterals name="synch"/>
    <eLiterals name="asynch" value="1"/>
    <eLiterals name="policy" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TechType">
    <eLiterals name="RDD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkflowOperation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
