<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="core" nsURI="http://io.github.dice-project/dtsm/core/1.0" nsPrefix="dtsm.core">
  <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
    <details key="name" value="DiceDomainModel::DTSM::Core"/>
    <details key="profileName" value="DICE::DICE_UML_Extensions::DTSM::Core"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DIAElement" abstract="true" interface="true">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents a generic element of the DIA at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::DIAElement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasProperty" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageNode" abstract="true" interface="true"
      eSuperTypes="#//DataSource">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents a storage node in the DIA implemented by a specific storage technology at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::StorageNode"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="database" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputeNode" abstract="true" interface="true"
      eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an element of the DIA performing a computation task by employing a specific data processing technology at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::ComputationNode"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procType" eType="#//ProcessingType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processData" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessors" upperBound="-1"
        eType="#//ComputeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realise" lowerBound="1"
        eType="#//Workflow"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produceOutputData" lowerBound="1"
        eType="#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" abstract="true" interface="true"
      eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an element of the DIA acting as a data source at the DTSM layer."/>
      <details key="extends" value="DiceDomainModel::DPIM::SourceNode"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="isConstrained" upperBound="-1"
        eType="#//Contraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasMetric" upperBound="-1"
        eType="#//Metric"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workflow" abstract="true" interface="true"
      eSuperTypes="#//DIAElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DAGNode" abstract="true" interface="true"
      eSuperTypes="#//DIAElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessors" upperBound="-1"
        eType="#//DAGNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produceOutput" eType="ecore:EClass dpim.ecore#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//WorkflowOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//DIAElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessingType">
    <eLiterals name="BATCH"/>
    <eLiterals name="STREAM" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TechType">
    <eLiterals name="Spark"/>
    <eLiterals name="HadoopMR"/>
    <eLiterals name="Storm"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ContraintType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ContraintType">
    <eLiterals name="LESS"/>
    <eLiterals name="LESSEQUAL" value="1"/>
    <eLiterals name="EQUAL" value="2"/>
    <eLiterals name="GREATER" value="4"/>
    <eLiterals name="GREATEREQUAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Metric" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapReduceJob" eSuperTypes="#//Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasMRPhase" lowerBound="1"
        upperBound="-1" eType="#//MapReducePhase"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectAcyclicGraph" abstract="true"
      interface="true" eSuperTypes="#//Workflow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="initialNode" lowerBound="1"
        upperBound="-1" eType="#//DAGSourceNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WorkflowOperation">
    <eLiterals name="GROUPBY"/>
    <eLiterals name="SUM" value="1"/>
    <eLiterals name="COUNT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapReducePhase" abstract="true" interface="true"
      eSuperTypes="#//DIAElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessors" upperBound="-1"
        eType="#//MapReducePhase"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasMap" eType="#//Map"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasReduce" eType="#//Reduce"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produceOutput" eType="ecore:EClass dpim.ecore#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Map" abstract="true" interface="true"
      eSuperTypes="#//DIAElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//MapType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reduce" abstract="true" interface="true"
      eSuperTypes="#//DIAElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parallelism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ReduceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MapType">
    <eLiterals name="RegexMapper" value="1"/>
    <eLiterals name="FieldSelectionMapper" value="2"/>
    <eLiterals name="ChainMapper"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ReduceType">
    <eLiterals name="FieldSelectionReduced"/>
    <eLiterals name="ChainReducer" value="1"/>
    <eLiterals name="IntSumReducer" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DAGSourceNode" eSuperTypes="#//DAGNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="readFrom" eType="ecore:EClass dpim.ecore#//StorageNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DICEProperty">
    <eLiterals name="SAFETY"/>
    <eLiterals name="PRIVACY" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass"/>
  <eSubpackages name="haddop" nsURI="http://io.github.dice-project/dtsm/hadoop-framework/1.0"
      nsPrefix="dtsm.hadoop"/>
  <eSubpackages name="storm" nsURI="http://io.github.dice-project/dtsm/storm-framework/1.0"
      nsPrefix="dtsm.storm"/>
  <eSubpackages name="spark" nsURI="http://io.github.dice-project/dtsm/spark-framework/1.0"
      nsPrefix="dtsm.spark"/>
</ecore:EPackage>
