<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="hadoop" nsURI="http://io.github.dice-project/dtsm/hadoop-framework/1.0"
    nsPrefix="dtsm.hadoop">
  <eClassifiers xsi:type="ecore:EClass" name="HadoopMRJob" eSuperTypes="../../io.github.dice-project.dtsm.core/model/dtsm.core.ecore#//MapReduceJob">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="job_reject_penalty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="think_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_cuncurrent_executions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_cuncurrent_executions"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="execution_time_deadline"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mapper" eSuperTypes="../../io.github.dice-project.dtsm.core/model/dtsm.core.ecore#//Map">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performance_profile" eType="#//MapPerformanceProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reducer" eSuperTypes="../../io.github.dice-project.dtsm.core/model/dtsm.core.ecore#//Reduce">
    <eStructuralFeatures xsi:type="ecore:EReference" name="performance_profile" eType="#//ReducePerformanceProfile"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scheduler">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduler_type" eType="#//SchedulerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Partitioner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="partitioner_type" eType="#//PartitionerType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Combiner">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="combiner_type" eType="ecore:EEnum ../../io.github.dice-project.dtsm.core/model/dtsm.core.ecore#//ReduceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HadoopMRApplication" eSuperTypes="../../io.github.dice-project.dtsm.core/model/dpim.ecore#//ComputeNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="combiner" eType="#//Combiner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scheduler" eType="#//Scheduler"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="partitioner" eType="#//Partitioner"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runOn" eType="#//YARN"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HadoopMRPhase" eSuperTypes="../../io.github.dice-project.dtsm.core/model/dtsm.core.ecore#//MapReducePhase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="execution_time_deadline"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reduce_number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="map_number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SchedulerType">
    <eLiterals name="FairScheduler"/>
    <eLiterals name="CapacityScheduler" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PartitionerType">
    <eLiterals name="BinaryPartitioner"/>
    <eLiterals name="HashPartitioner" value="1"/>
    <eLiterals name="KeyFieldBasedPartitioner" value="2"/>
    <eLiterals name="TotalOrderPartitioner" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YARNNodeManager">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_check_interval"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="health_check_timeout" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_healty_disks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_disk_utilization" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YARNResourceManager">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="client_thread_count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodemanager_connect_retry_time"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="application_master_timeout"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="application_master_max_attempts"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="container_liveness_monitor_frequency"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="node_manager_liveness_timeout"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_container_ram" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_container_ram" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="min_container_ncore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_container_ncore" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nodemanagers_heartbeat_interval"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="YARN">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasMasterNode" lowerBound="1"
        eType="#//YARNResourceManager"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSlaveNodes" lowerBound="1"
        eType="#//YARNNodeManager"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MapPerformanceProfile" eSuperTypes="#//PerformanceProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_exec_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean_exec_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vmType" lowerBound="1"
        eType="ecore:EEnum ../../io.github.dice-project.ddsm/model/ddsm.ecore#//VMSize"
        changeable="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ReducePerformanceProfile" eSuperTypes="#//PerformanceProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_exec_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean_exec_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="max_shuffle_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mean_shuffle_time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceProfile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="performanceProfileId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceVm" lowerBound="1"
        eType="ecore:EEnum ../../io.github.dice-project.ddsm/model/ddsm.ecore#//VMSize"
        changeable="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="referenceProvider" eType="ecore:EEnum ../../io.github.dice-project.ddsm/model/ddsm.ecore#//ProviderType"/>
  </eClassifiers>
</ecore:EPackage>
