<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dpim" nsURI="http://io.github.dice-project/dpim/1.0" nsPrefix="dpim">
  <eAnnotations source="propertiesRestrictions">
    <details key="ComputationNodePropertyRestrictions"/>
    <details key="SourceNodePropertyRestrictions"/>
    <details key="StorageElementPropertyRestrictions"/>
  </eAnnotations>
  <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
    <details key="name" value="DiceDomainModel::DPIM"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DIA">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents a Data Intensive Application."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        upperBound="-1" eType="#//DIAElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DIAElement" abstract="true">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="An element of a Data Intensive Application. It can be a ComputationNode or a StorageNode."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasToFullfill" upperBound="-1"
        eType="#//QoSRequiredProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputeNode" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents an element of the application whose goal is to perform some computation."/>
      <details key="extends" value="DAM::System::Core::Component"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetTech" eType="#//ComputeTechType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procType" eType="#//ProcessingType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="processInputData" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasSuccessors" upperBound="-1"
        eType="#//ComputeNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeOutput" upperBound="-1"
        eType="#//StorageNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="produceOutputData" eType="#//Data"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSource" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an element of the DIA acting as a data source at the DPIM layer."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" eType="#//DataSourceSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//DataSourceType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageNode" eSuperTypes="#//DataSource">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Reseprents an element of the application whose goal is to store the application data, (i.e, a database or a file system)."/>
      <details key="extends" value="MARTE::GRM::ResourceCore::StorageResource"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CRUDrate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="user" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="password" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSourceSpecification">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents data characteristics like the model and the format."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataModel" eType="#//DataModelType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QoSRequiredProperty">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents the QoS constraints associated with an element of the Data Intensive Applicaion."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents the data that an element of the application can take in input and/or produce in output."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="shema" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" eType="#//DataSource"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComputeTechType">
    <eLiterals name="Spark"/>
    <eLiterals name="HadoopMR" value="1"/>
    <eLiterals name="Storm" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessingType">
    <eLiterals name="StreamProcessing"/>
    <eLiterals name="BatchProcesisng" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataModelType">
    <eLiterals name="Columnar"/>
    <eLiterals name="DocumentBased" value="1"/>
    <eLiterals name="Relational" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataSourceType">
    <eLiterals name="Cassandra"/>
    <eLiterals name="MySQL" value="1" literal=""/>
    <eLiterals name="MongoDB" value="2"/>
    <eLiterals name="HDFS" value="3"/>
  </eClassifiers>
</ecore:EPackage>
