<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="dpim" nsURI="http://io.github.dice-project/dpim/1.0" nsPrefix="dpim">
  <eAnnotations source="propertiesRestrictions" references="#//DICEproperties">
    <details key="ComputationNodePropertyRestrictions"/>
    <details key="SourceNodePropertyRestrictions"/>
    <details key="StorageElementPropertyRestrictions"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SourceNode" eSuperTypes="#//ComputationNode">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents an element of the DIA acting as a data source at the DPIM layer."/>
      <details key="extends" value="ComputationNode"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="provides" eType="#//DataSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceType" eType="#//SourceType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceProperties" upperBound="-1"
        eType="#//DICEproperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataSpecification">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="This entity represents data characteristics like the model and the format."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="#//DICEproperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refERmodel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="refDataFormat" eType="#//DataFormatType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComputationNode" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents an element of the application whose goal is to perform some computation."/>
      <details key="extends" value="DIAElement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ComputationType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetTech" eType="#//TechType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="procType" eType="#//ProcessingType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="thorughput" eType="#//DICEproperties"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="storeAndProcess" upperBound="-1"
        eType="#//StorageNode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComputationType">
    <eLiterals name="distributed"/>
    <eLiterals name="parallel" value="1"/>
    <eLiterals name="distributedParallel" value="2"/>
    <eLiterals name="microBench" value="3"/>
    <eLiterals name="sorting" value="4"/>
    <eLiterals name="grep" value="5"/>
    <eLiterals name="wordCount" value="6"/>
    <eLiterals name="collabFiltering" value="7"/>
    <eLiterals name="naiveBayes" value="8"/>
    <eLiterals name="bfs" value="9"/>
    <eLiterals name="pageRank" value="10"/>
    <eLiterals name="kMeans" value="11"/>
    <eLiterals name="connectedComponents" value="12"/>
    <eLiterals name="relQuery" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TechType">
    <eLiterals name="RDD"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SourceType">
    <eLiterals name="sharedStorage"/>
    <eLiterals name="dataStream" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ProcessingType">
    <eLiterals name="synch"/>
    <eLiterals name="asynch" value="1"/>
    <eLiterals name="policy" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Channel">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents a communication channel between a ComputationNode and a StorageNode."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectsOne" lowerBound="1"
        upperBound="-1" eType="#//ComputationNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectsTwo" lowerBound="1"
        upperBound="-1" eType="#//StorageNode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rate" eType="#//DICEproperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StorageNode" eSuperTypes="#//DIAElement">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Reseprents an element of the application whose goal is to store the application data,( i.e a database or a file system)."/>
      <details key="extends" value="DIAElement"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responds_to" lowerBound="1"
        eType="#//DataSpecification"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="CRUDrate" eType="#//DICEproperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="properties" lowerBound="1"
        upperBound="-1" eType="#//DICEproperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DICEproperties">
    <eLiterals name="genericProperty"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DIA">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents a Data Intensive Application."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        upperBound="-1" eType="#//DIAElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DIAElement" abstract="true">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="An element of a Data Intensive Application. It can be a ComputationNode or a StorageNode."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasToFullfill" lowerBound="1"
        upperBound="-1" eType="#//QoSRequiredProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contains" lowerBound="1"
        upperBound="-1" eType="#//DIAElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="input" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="output" upperBound="-1"
        eType="#//Data"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredProperties" lowerBound="1"
        upperBound="-1" eType="#//DICEproperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="providedProperties" lowerBound="1"
        upperBound="-1" eType="#//DICEproperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QoSRequiredProperty">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents the QoS constraints associated with an element of the Data Intensive Applicaion."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FilterNode" eSuperTypes="#//ComputationNode">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents a computation node that performs just some filtering on the application data."/>
      <details key="extends" value="ComputationNode"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="inputRatio" eType="#//DICEproperties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="outputRatio" eType="#//DICEproperties"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VisualizationNode" eSuperTypes="#//ComputationNode">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents a computation node whose goal is to perform data visualization."/>
      <details key="extends" value="ComputationNode"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Data">
    <eAnnotations source="http://es.unizar.disco/dice/profiles/generator">
      <details key="description" value="Represents the data that an element of the application can take in input and/or produce in output."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="responds_to" eType="#//DataSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataFormatType"/>
  <eSubpackages name="DICETypes"/>
</ecore:EPackage>
